#!/usr/bin/env node
/**
 * server.ts — MCP server for the engram memory bank.
 *
 * What this file is: a local stdio MCP server that exposes session memory,
 *   handoff context, and knowledge graph as queryable tools.
 * Responsible for: serving memory bank data to any MCP-capable AI assistant
 *   (Claude Code, Gemini CLI, VS Code Copilot, OpenCode, Codex CLI, Cursor).
 *   Runs as a spawned local process — no remote server or hosting needed.
 * Depends on: @modelcontextprotocol/sdk, better-sqlite3, js-yaml, zod,
 *   src/memory/working.ts, src/handoff/writer.ts.
 * Depended on by: any MCP host that configures it (assistant-specific config
 *   files written by src/cli/setup.ts).
 *
 * Usage:
 *   Project-local setup (generated by setup CLI):
 *     { "command": "node", "args": ["/path/to/build/mcp/server.js"] }
 *
 *   npm self-install / assistant-managed setup:
 *     npx --yes --package=@morous-dev/engram-cc -- engramcc-mcp
 *
 *   Do not guess:
 *     npx @morous-dev/engram-cc mcp
 *
 * IMPORTANT: Never write to stdout except via the MCP SDK transport.
 *   All logging must use console.error() — stdout is reserved for JSON-RPC.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { getProjectDBPath } from "../project-id.js";
import Database from "better-sqlite3";
import yaml from "js-yaml";
import type { WorkingMemory } from "../memory/working.js";
import type { HandoffData } from "../handoff/writer.js";

// ── DB path helpers ──────────────────────────────────────────────────────────

/**
 * Compute the SQLite DB path for a project using stable project UUID.
 * Delegates to getProjectDBPath() — path: <projectDir>/.engram-cc/sessions/<uuid>.db
 *
 * @param projectDir - Absolute path to the project directory.
 * @returns Absolute path to the project's SQLite DB file.
 */
function getDbPath(projectDir: string): string {
  return getProjectDBPath(projectDir);
}

/**
 * Open the project DB in read-only mode.
 * Returns null if the DB does not exist yet (no sessions for this project).
 *
 * @param projectDir - Absolute path to the project directory.
 */
function openDb(projectDir: string): Database.Database | null {
  const dbPath = getDbPath(projectDir);
  if (!existsSync(dbPath)) return null;
  try {
    return new Database(dbPath, { readonly: true, fileMustExist: true });
  } catch {
    return null;
  }
}

// ── YAML file helpers ────────────────────────────────────────────────────────

function readHandoff(projectDir: string): HandoffData | null {
  const path = join(projectDir, ".engram-cc", "handoff.yaml");
  if (!existsSync(path)) return null;
  try {
    return yaml.load(readFileSync(path, "utf-8")) as HandoffData;
  } catch {
    return null;
  }
}

function readWorking(projectDir: string): WorkingMemory | null {
  const path = join(projectDir, ".engram-cc", "working.yaml");
  if (!existsSync(path)) return null;
  try {
    return yaml.load(readFileSync(path, "utf-8")) as WorkingMemory;
  } catch {
    return null;
  }
}

// ── MCP Server setup ─────────────────────────────────────────────────────────

const server = new McpServer({
  name: "engram-cc",
  version: "0.1.0",
});

// ── Tool: recall ─────────────────────────────────────────────────────────────

/**
 * recall — "What was I working on?"
 * Returns the full session handoff + working memory for a project.
 * This is the primary tool — call it at the start of every session.
 *
 * Parameters:
 *   projectDir (optional) — defaults to process.cwd()
 */
server.tool(
  "recall",
  "Get full session context: last handoff, working memory, decisions, files modified. Call this at the start of every session.",
  {
    projectDir: z.string().optional().describe(
      "Absolute path to the project directory. Defaults to the current working directory.",
    ),
  },
  async ({ projectDir }) => {
    const dir = projectDir ?? process.cwd();
    const handoff = readHandoff(dir);
    const working = readWorking(dir);

    if (!handoff && !working) {
      return {
        content: [{
          type: "text",
          text: `No session memory found for project: ${dir}\nThis is either a new project or the session hooks have not fired yet.`,
        }],
      };
    }

    const sections: string[] = [`# Session Memory — ${dir}\n`];

    if (handoff) {
      sections.push("## Last Session Handoff");
      sections.push(`- **When:** ${handoff.timestamp}`);
      sections.push(`- **Task:** ${handoff.current_task || "(none)"}`);
      sections.push(`- **Last action:** ${handoff.last_action || "(none)"}`);
      sections.push(`- **Context:** ${handoff.working_context || "(none)"}`);
      sections.push(`- **Confidence:** ${handoff.confidence}`);

      if (handoff.next_steps?.length) {
        sections.push("\n**Next steps:**");
        for (const s of handoff.next_steps) sections.push(`  - ${s}`);
      }
      if (handoff.decisions?.length) {
        sections.push("\n**Decisions made:**");
        for (const d of handoff.decisions) sections.push(`  - ${d}`);
      }
      if (handoff.files_modified?.length) {
        sections.push("\n**Files modified:**");
        for (const f of handoff.files_modified) sections.push(`  - ${f}`);
      }
      if (handoff.blockers?.length) {
        sections.push("\n**Blockers:**");
        for (const b of handoff.blockers) sections.push(`  - ${b}`);
      }
      if (handoff.open_questions?.length) {
        sections.push("\n**Open questions:**");
        for (const q of handoff.open_questions) sections.push(`  - ${q}`);
      }
    }

    if (working) {
      sections.push("\n## Working Memory (cross-session)");
      if (working.user_preferences)     sections.push(`- **Preferences:** ${working.user_preferences}`);
      if (working.codebase_conventions) sections.push(`- **Conventions:** ${working.codebase_conventions}`);
      if (working.persistent_decisions?.length) {
        sections.push("- **Persistent decisions:**");
        for (const d of working.persistent_decisions.slice(-10)) sections.push(`  - ${d}`);
      }
      if (working.frequently_modified_files?.length) {
        sections.push(`- **Hot files:** ${working.frequently_modified_files.slice(0, 10).join(", ")}`);
      }
    }

    return { content: [{ type: "text", text: sections.join("\n") }] };
  },
);

// ── MCP search query preprocessor ────────────────────────────────────────────

/**
 * Stop-words removed from MCP search queries before FTS5 matching.
 * Question words and auxiliaries appear in user queries ("What did we decide
 * about auth?") but almost never in event text, so AND-joining them returns
 * zero results. Stripped before building the tiered FTS5 query.
 */
const SEARCH_STOP_WORDS = new Set([
  // Question words
  "what", "when", "where", "who", "whom", "which", "why", "how",
  // Auxiliary verbs
  "did", "do", "does", "is", "are", "was", "were", "has", "have", "had",
  "will", "would", "could", "should", "can", "may", "might",
  // Articles + common fillers
  "the", "a", "an", "of", "in", "to", "for", "on", "at", "by",
  "from", "with", "about", "into", "that", "this", "we", "our", "us",
]);

/**
 * Build a tiered FTS5 query from a raw natural-language search string.
 *
 * Natural-language queries from assistants include question words and
 * auxiliary verbs ("When did we decide about auth?") that never appear in
 * stored event text, causing FTS5 AND-matching to return zero results.
 *
 * This function strips stop-words, then tries three increasingly relaxed
 * AND-joined query tiers before falling back to OR-join (broad recall):
 *
 *   strict  — top 4 content terms AND-joined
 *   relaxed — top 3 content terms AND-joined (if strict returns nothing)
 *   minimal — top 2 content terms AND-joined (if relaxed returns nothing)
 *   broad   — all terms OR-joined (last resort, used by caller)
 *
 * If the raw query is already valid FTS5 (contains AND/OR/NOT/"phrase"),
 * it is returned as-is so power users retain full FTS5 syntax control.
 *
 * @param raw - Raw user query string
 * @returns Object with strict/relaxed/minimal/broad tier strings and
 *   isFts5Syntax flag indicating the raw query should be passed through.
 */
function buildSearchQuery(raw: string): {
  strict: string;
  relaxed: string;
  minimal: string;
  broad: string;
  isFts5Syntax: boolean;
} {
  const trimmed = raw.trim();

  // Pass through explicit FTS5 syntax (contains operators or phrase quotes)
  if (/\b(AND|OR|NOT)\b|"/.test(trimmed)) {
    return { strict: trimmed, relaxed: trimmed, minimal: trimmed, broad: trimmed, isFts5Syntax: true };
  }

  const terms = trimmed
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(t => t.length >= 3 && !SEARCH_STOP_WORDS.has(t));

  if (terms.length === 0) {
    // Nothing useful after filtering — pass the original through unchanged.
    return { strict: trimmed, relaxed: trimmed, minimal: trimmed, broad: trimmed, isFts5Syntax: true };
  }

  const strict  = terms.slice(0, 4).join(" ");
  const relaxed = terms.slice(0, 3).join(" ");
  const minimal = terms.slice(0, 2).join(" ");
  const broad   = terms.join(" OR ");

  return { strict, relaxed, minimal, broad, isFts5Syntax: false };
}

// ── Tool: search ─────────────────────────────────────────────────────────────

/**
 * search — "When did we decide X? What happened with Y?"
 * Full-text search over all session events using SQLite FTS5.
 *
 * Parameters:
 *   query      — FTS5 search query (supports AND, OR, NOT, phrase "exact match")
 *   projectDir — defaults to process.cwd()
 *   limit      — max results, default 10
 */
server.tool(
  "search",
  "Full-text search over session memory. Find past decisions, errors, file changes, and context by keyword.",
  {
    query: z.string().describe('Search query. Supports FTS5 operators: AND, OR, NOT, "phrase search".'),
    projectDir: z.string().optional().describe("Project directory. Defaults to cwd."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results. Default 10."),
  },
  async ({ query, projectDir, limit = 10 }) => {
    const dir = projectDir ?? process.cwd();
    const db = openDb(dir);

    if (!db) {
      return {
        content: [{ type: "text", text: `No session DB found for: ${dir}` }],
      };
    }

    try {
      // Check FTS table exists before querying
      const hasFts = db.prepare(
        `SELECT name FROM sqlite_master WHERE type='table' AND name='session_events_fts'`,
      ).get();

      if (!hasFts) {
        return {
          content: [{ type: "text", text: "FTS index not yet built for this project." }],
        };
      }

      interface EventRow {
        type: string;
        category: string;
        data: string;
        created_at: string;
        session_id: string;
        source_assistant: string;
        source_kind: string;
        source_confidence: string;
      }

      // Build tiered FTS5 query from the raw user input.
      // Natural-language queries contain question words and auxiliaries that
      // never appear in event text, causing AND-match to return zero results.
      // The tiered approach tries strict→relaxed→minimal AND-joins, then falls
      // back to OR-join for maximum recall before giving up.
      const searchTiers = buildSearchQuery(query);
      const searchLive = db.prepare<[string, number], EventRow>(`
        SELECT e.type, e.category, e.data, e.created_at, e.session_id,
               e.source_assistant, e.source_kind, e.source_confidence
        FROM session_events e
        JOIN session_events_fts fts ON e.id = fts.rowid
        WHERE session_events_fts MATCH ?
        ORDER BY e.created_at DESC
        LIMIT ?
      `);

      let rows: EventRow[] = searchLive.all(searchTiers.strict, limit);
      if (!rows.length && !searchTiers.isFts5Syntax) {
        rows = searchLive.all(searchTiers.relaxed, limit);
      }
      if (!rows.length && !searchTiers.isFts5Syntax) {
        rows = searchLive.all(searchTiers.minimal, limit);
      }
      if (!rows.length && !searchTiers.isFts5Syntax) {
        rows = searchLive.all(searchTiers.broad, limit);
      }

      // Also search archive for evicted events (same tiered strategy)
      let archiveRows: EventRow[] = [];
      try {
        const hasArchiveFts = db.prepare(
          `SELECT name FROM sqlite_master WHERE type='table' AND name='session_events_archive_fts'`,
        ).get();
        if (hasArchiveFts) {
          const searchArchive = db.prepare<[string, number], EventRow>(`
            SELECT a.type, a.category, a.data, a.created_at, a.session_id,
                   a.source_assistant, a.source_kind, a.source_confidence
            FROM session_events_archive a
            JOIN session_events_archive_fts fts ON a.id = fts.rowid
            WHERE session_events_archive_fts MATCH ?
            ORDER BY a.created_at DESC
            LIMIT ?
          `);

          archiveRows = searchArchive.all(searchTiers.strict, limit);
          if (!archiveRows.length && !searchTiers.isFts5Syntax) {
            archiveRows = searchArchive.all(searchTiers.relaxed, limit);
          }
          if (!archiveRows.length && !searchTiers.isFts5Syntax) {
            archiveRows = searchArchive.all(searchTiers.broad, limit);
          }
        }
      } catch { /* older DB without archive */ }

      // Merge live + archive, deduplicate by content prefix
      const seen = new Set<string>();
      const finalRows: EventRow[] = [];
      for (const r of [...rows, ...archiveRows]) {
        const key = r.data.slice(0, 200);
        if (seen.has(key)) continue;
        seen.add(key);
        finalRows.push(r);
      }
      const resultRows = finalRows.slice(0, limit);

      if (!resultRows.length) {
        return { content: [{ type: "text", text: `No results for: "${query}"` }] };
      }

      const lines = [`# Search results for "${query}" (${resultRows.length} found)\n`];
      for (const row of resultRows) {
        lines.push(
          `**[${row.category}/${row.type}]** ${row.created_at.slice(0, 19)} (${row.source_assistant}/${row.source_kind}/${row.source_confidence})`,
        );
        lines.push(`  ${row.data.slice(0, 300)}`);
        lines.push("");
      }

      return { content: [{ type: "text", text: lines.join("\n") }] };
    } finally {
      db.close();
    }
  },
);

// ── Tool: recent ─────────────────────────────────────────────────────────────

/**
 * recent — "What happened in the last session?"
 * Returns the most recent N session events, optionally filtered by category.
 *
 * Parameters:
 *   projectDir — defaults to process.cwd()
 *   limit      — max events, default 20
 *   category   — filter by category (file, task, decision, error, prompt)
 */
server.tool(
  "recent",
  "Get the most recent session events. Useful for understanding what happened in the last session.",
  {
    projectDir: z.string().optional().describe("Project directory. Defaults to cwd."),
    limit: z.number().int().min(1).max(100).optional().describe("Number of events. Default 20."),
    category: z.enum(["file", "task", "decision", "error", "prompt", "tool"]).optional()
      .describe("Filter by event category."),
  },
  async ({ projectDir, limit = 20, category }) => {
    const dir = projectDir ?? process.cwd();
    const db = openDb(dir);

    if (!db) {
      return { content: [{ type: "text", text: `No session DB found for: ${dir}` }] };
    }

    try {
      interface EventRow {
        type: string;
        category: string;
        data: string;
        created_at: string;
        source_assistant: string;
        source_kind: string;
        source_confidence: string;
      }

      const rows = category
        ? db.prepare<[string, number], EventRow>(`
            SELECT type, category, data, created_at, source_assistant, source_kind, source_confidence FROM session_events
            WHERE category = ?
            ORDER BY created_at DESC LIMIT ?
          `).all(category, limit)
        : db.prepare<[number], EventRow>(`
            SELECT type, category, data, created_at, source_assistant, source_kind, source_confidence FROM session_events
            ORDER BY created_at DESC LIMIT ?
          `).all(limit);

      if (!rows.length) {
        return { content: [{ type: "text", text: "No session events recorded yet." }] };
      }

      const lines = [`# Recent events — ${dir}\n`];
      for (const row of rows) {
        lines.push(
          `**${row.created_at.slice(0, 19)}** [${row.category}/${row.type}] (${row.source_assistant}/${row.source_kind}/${row.source_confidence})`,
        );
        lines.push(`  ${row.data.slice(0, 200)}`);
        lines.push("");
      }

      return { content: [{ type: "text", text: lines.join("\n") }] };
    } finally {
      db.close();
    }
  },
);

// ── Tool: semantic_search ────────────────────────────────────────────────────

/**
 * semantic_search — "What did we decide about databases?" (meaning-based)
 * Vector similarity search over embedded session events using sqlite-vec.
 * Unlike FTS5 keyword search, this finds semantically similar content even
 * when exact words don't match (e.g., "database choice" finds "PostgreSQL
 * selected over MongoDB").
 *
 * This is the mid-conversation retrieval tool — Claude can call it anytime,
 * not just at compaction boundaries. It queries the same vec_procedures table
 * that the Stop hook populates with embeddings of decisions, errors, tasks,
 * and rules.
 *
 * Parameters:
 *   query      — natural language query (embedded via MiniLM-L6-v2)
 *   projectDir — defaults to process.cwd()
 *   limit      — max results, default 10
 */
server.tool(
  "semantic_search",
  "Semantic similarity search over session memory. Finds related decisions, errors, and context by meaning, not just keywords. Use when keyword search fails or when you need conceptually related facts.",
  {
    query: z.string().describe("Natural language query describing what you're looking for."),
    projectDir: z.string().optional().describe("Project directory. Defaults to cwd."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results. Default 10."),
  },
  async ({ query, projectDir, limit = 10 }) => {
    const dir = projectDir ?? process.cwd();
    const dbPath = getDbPath(dir);

    if (!existsSync(dbPath)) {
      return { content: [{ type: "text", text: `No session DB found for: ${dir}` }] };
    }

    try {
      // Lazy-load vector and embedding dependencies
      const { VectorDB } = await import("../memory/vector.js");
      const { getCompressor } = await import("../compression/index.js");

      const vectorDB = new VectorDB(dbPath);

      if (!vectorDB.isAvailable()) {
        vectorDB.close();
        return {
          content: [{ type: "text", text: "Vector search unavailable (sqlite-vec not loaded). Use the 'search' tool for keyword-based search instead." }],
        };
      }

      // Generate query embedding using the compressor's embed pipeline (MiniLM-L6-v2)
      const compressor = getCompressor();
      const embedResult = await compressor.embed([query]);

      if (embedResult.embeddings.length === 0 || embedResult.dimensions === 0) {
        vectorDB.close();
        return {
          content: [{ type: "text", text: "Embedding generation failed. Use the 'search' tool for keyword-based search instead." }],
        };
      }

      const results = vectorDB.search(embedResult.embeddings[0], limit);
      vectorDB.close();

      if (results.length === 0) {
        return { content: [{ type: "text", text: `No semantic matches for: "${query}"` }] };
      }

      const lines = [`# Semantic search: "${query}" (${results.length} matches)\n`];
      for (const r of results) {
        const confidence = Math.max(0, 1.0 - r.distance).toFixed(2);
        const meta = r.metadata as Record<string, unknown>;
        const cat = typeof meta.category === "string" ? meta.category : "unknown";
        const typ = typeof meta.type === "string" ? meta.type : "";
        lines.push(`**[${cat}${typ ? "/" + typ : ""}]** (confidence: ${confidence})`);
        lines.push(`  ${r.content.slice(0, 400)}`);
        lines.push("");
      }

      return { content: [{ type: "text", text: lines.join("\n") }] };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return {
        content: [{ type: "text", text: `Semantic search failed: ${msg}\nFallback: use the 'search' tool for keyword search.` }],
      };
    }
  },
);

// ── Tool: graph_query ────────────────────────────────────────────────────────

/**
 * graph_query — "What relates to this file / concept?"
 * BFS traversal of the knowledge graph up to a given depth.
 *
 * Parameters:
 *   label      — node label to start from (file path, concept name, etc.)
 *   projectDir — defaults to process.cwd()
 *   depth      — BFS depth, default 2
 */
server.tool(
  "graph_query",
  "Query the knowledge graph. Find files, concepts, and decisions related to a given topic or file path.",
  {
    label: z.string().describe("Node label to query (file path, concept name, decision keyword)."),
    projectDir: z.string().optional().describe("Project directory. Defaults to cwd."),
    depth: z.number().int().min(1).max(4).optional().describe("BFS traversal depth. Default 2."),
  },
  async ({ label, projectDir, depth = 2 }) => {
    const dir = projectDir ?? process.cwd();
    const db = openDb(dir);

    if (!db) {
      return { content: [{ type: "text", text: `No session DB found for: ${dir}` }] };
    }

    try {
      const hasGraph = db.prepare(
        `SELECT name FROM sqlite_master WHERE type='table' AND name='graph_nodes'`,
      ).get();

      if (!hasGraph) {
        return { content: [{ type: "text", text: "Knowledge graph not yet built for this project." }] };
      }

      interface NodeRow { id: string; type: string; label: string; }
      interface EdgeRow { from_node: string; to_node: string; relation: string; }

      // Find seed node
      const seed = db.prepare<[string, string], NodeRow>(
        `SELECT id, type, label FROM graph_nodes WHERE project_dir = ? AND label LIKE ? LIMIT 1`,
      ).get(dir, `%${label}%`);

      if (!seed) {
        return { content: [{ type: "text", text: `No graph node found matching: "${label}"` }] };
      }

      // BFS traversal
      const visited = new Set<string>([seed.id]);
      const queue: Array<{ id: string; depth: number }> = [{ id: seed.id, depth: 0 }];
      const results: string[] = [`# Knowledge graph — "${label}"\n`, `**Seed:** [${seed.type}] ${seed.label}\n`];

      while (queue.length > 0) {
        const current = queue.shift()!;
        if (current.depth >= depth) continue;

        const edges = db.prepare<[string, string, string, string], EdgeRow & { neighbor_label: string; neighbor_type: string }>(
          `SELECT e.from_node, e.to_node, e.relation, n.label as neighbor_label, n.type as neighbor_type
           FROM graph_edges e
           JOIN graph_nodes n ON e.to_node = n.id
           WHERE e.from_node = ? AND e.project_dir = ?
           UNION ALL
           SELECT e.from_node, e.to_node, e.relation, n.label as neighbor_label, n.type as neighbor_type
           FROM graph_edges e
           JOIN graph_nodes n ON e.from_node = n.id
           WHERE e.to_node = ? AND e.project_dir = ?
           LIMIT 20`,
        ).all(current.id, dir, current.id, dir);

        for (const edge of edges) {
          const neighborId = edge.from_node === current.id ? edge.to_node : edge.from_node;
          if (visited.has(neighborId)) continue;
          visited.add(neighborId);

          const indent = "  ".repeat(current.depth + 1);
          results.push(`${indent}→ **${edge.relation}** [${edge.neighbor_type}] ${edge.neighbor_label}`);
          queue.push({ id: neighborId, depth: current.depth + 1 });
        }
      }

      if (results.length === 2) results.push("No connected nodes found.");

      return { content: [{ type: "text", text: results.join("\n") }] };
    } finally {
      db.close();
    }
  },
);

// ── Start server ─────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("[engram-cc] MCP server running on stdio");
}

main().catch(err => {
  console.error("[engram] Fatal:", err instanceof Error ? err.message : String(err));
  process.exit(1);
});
