/**
 * writer.ts — YAML session handoff writer.
 *
 * Responsible for: building a HandoffData structure from session events +
 * transcript context, and writing it to the YAML handoff file. The handoff
 * YAML is the primary cross-session memory artifact — it is read by the next
 * session's SessionStart hook.
 *
 * When a Compressor is provided (optional), the local SLM synthesizes
 * `working_context` and `headline` from session events. Without a Compressor
 * both fields fall back to heuristic derivation from transcript messages.
 * All other fields remain rule-based regardless of compressor availability.
 *
 * Depends on: js-yaml, node:fs, node:path, node:os, node:crypto,
 *             src/handoff/dedup.ts, src/truncate.ts, src/session/db.ts,
 *             src/compression/types.ts (optional, for SLM synthesis).
 * Depended on by: src/hooks/stop.ts.
 */

import yaml from "js-yaml";
import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import type { TranscriptContext } from "./dedup.js";
import type { StoredEvent, ResumeHistoryRow } from "../session/db.js";
import type { WorkingMemory } from "../memory/working.js";
import { truncateString } from "../truncate.js";

// ── Types ─────────────────────────────────────────────────────────────────────

/**
 * The 16-section handoff YAML format.
 * Written by the Stop hook, read by the next SessionStart.
 */
export interface HandoffData {
  /** Session UUID. */
  session_id: string;
  /** ISO-8601 timestamp of when the handoff was written. */
  timestamp: string;
  /** Absolute path to the project directory. */
  project_dir: string;
  /** What the user was working on when the session ended. */
  current_task: string;
  /** Last file operation or significant action taken. */
  last_action: string;
  /** Pending next steps extracted from task events and user prompts. */
  next_steps: string[];
  /** Key decisions made during the session. */
  decisions: string[];
  /** Files modified during the session. */
  files_modified: string[];
  /** Errors encountered during the session. */
  errors_encountered: string[];
  /** Errors that were subsequently resolved. */
  errors_resolved: string[];
  /** Summary of what the session was doing, from user messages or SLM synthesis. */
  working_context: string;
  /**
   * One-line summary generated by local SLM (or truncated current_task as fallback).
   * Used for tiered injection — shown instead of the full handoff on cold starts.
   * Optional so old YAML handoffs without this field remain valid after deserialization.
   */
  headline?: string;
  /** User preferences observed (tools, OS, style). */
  user_preferences: string;
  /** Codebase conventions observed (module system, naming, patterns). */
  codebase_conventions: string;
  /** Open questions or unresolved decisions. */
  open_questions: string[];
  /** Blockers: errors or issues that were NOT resolved. */
  blockers: string[];
  /** Estimated confidence in the handoff completeness. */
  confidence: "high" | "medium" | "low";
}

// ── Path helpers ──────────────────────────────────────────────────────────────

/**
 * Get the handoff YAML file path for a given project directory.
 * Path: [projectDir]/.engram-cc/handoff.yaml
 * Creates the directory if it doesn't exist.
 *
 * @param projectDir - Absolute path to the project directory.
 * @returns Absolute path to the handoff YAML file.
 */
export function getHandoffPath(projectDir: string): string {
  const dir = join(projectDir, ".engram-cc");
  mkdirSync(dir, { recursive: true });
  return join(dir, "handoff.yaml");
}

// ── Synthesis input builder ───────────────────────────────────────────────────

/**
 * Build a structured plain-text blob from session events for the local SLM
 * to summarize into `working_context` and `headline`.
 *
 * Only includes sections that have data. Returns an empty string when all
 * source arrays are empty so the caller can skip the SLM call entirely.
 *
 * @param promptEvents           - "prompt" category events for the session.
 * @param decisionEvents         - "decision" category events for the session.
 * @param filesModified          - Deduplicated list of modified file paths.
 * @param errors                 - Truncated error strings from the session.
 * @param priorCompactionBriefs  - SLM briefs from earlier compaction cycles, oldest
 *                                 first. When present, prepended before tail events so
 *                                 the SLM synthesizes the full session arc, not just
 *                                 the final segment.
 * @returns Formatted plain-text block, or empty string if no data.
 */
export function buildSynthesisInput(
  promptEvents: StoredEvent[],
  decisionEvents: StoredEvent[],
  filesModified: string[],
  errors: string[],
  errorsResolved: string[],
  currentTask: string,
  lastAction: string,
  priorCompactionBriefs?: string[],
): string {
  const sections: string[] = [];

  // Prior compaction cycles — prepend before tail so the SLM sees the full
  // session arc. Each brief summarizes everything up to that compaction point.
  // The tail events below cover only the most recent cycle.
  if (priorCompactionBriefs && priorCompactionBriefs.length > 0) {
    // Cap at 5 most recent cycles — prevents SLM context saturation on very long
    // sessions. Oldest cycles are already summarized inside the later briefs.
    const recentBriefs = priorCompactionBriefs.slice(-5);
    const offset = priorCompactionBriefs.length - recentBriefs.length;
    sections.push("Session history from prior compaction cycles:");
    for (let i = 0; i < recentBriefs.length; i++) {
      sections.push(`[Cycle ${i + 1 + offset}] ${truncateString(recentBriefs[i], 600)}`);
    }
    sections.push("--- Current session tail (most recent events) ---");
  }

  // Current state — most important for the next session
  if (currentTask) sections.push(`Current task: ${currentTask}`);
  if (lastAction) sections.push(`Last action: ${lastAction}`);

  // User intent — what they asked for, in order.
  // slice(-7) covers the tail of the session; prior cycles are covered above.
  const recentPrompts = promptEvents.slice(-7);
  if (recentPrompts.length > 0) {
    sections.push("User requests (chronological):");
    for (const e of recentPrompts) sections.push(`- ${truncateString(e.data, 150)}`);
  }

  // Decisions — the SLM should detect conflicts and report final state.
  // Prior-cycle decisions are covered by the priorCompactionBriefs above.
  const recentDecisions = decisionEvents.slice(-7);
  if (recentDecisions.length > 0) {
    sections.push("Decisions made:");
    for (const e of recentDecisions) sections.push(`- ${truncateString(e.data, 150)}`);
  }

  // Files modified — concrete evidence of what changed
  const recentFiles = filesModified.slice(-15);
  if (recentFiles.length > 0) {
    sections.push(`Files modified (${filesModified.length} total):`);
    for (const f of recentFiles) sections.push(`- ${f}`);
  }

  // Errors — distinguish unresolved from resolved
  const resolvedSet = new Set(errorsResolved.map(e => e.slice(0, 80)));
  const unresolvedErrors = errors.filter(e => !resolvedSet.has(e.slice(0, 80)));
  if (unresolvedErrors.length > 0) {
    sections.push("Unresolved errors:");
    for (const err of unresolvedErrors.slice(-3)) sections.push(`- ${err}`);
  }
  if (errorsResolved.length > 0) {
    sections.push(`Resolved errors: ${errorsResolved.length} fixed`);
  }

  return sections.join("\n");
}

// ── Builder ───────────────────────────────────────────────────────────────────

/**
 * Build a HandoffData structure from session events, transcript context,
 * and the project's working memory.
 *
 * This function synthesizes all available session data into the 16-section
 * handoff format. When a Compressor is supplied, the local SLM generates
 * `working_context` and `headline` from session events (zero external API
 * calls). Both fields fall back to heuristic derivation if the SLM is
 * unavailable or produces empty output. All other fields remain rule-based.
 *
 * The transcript context (from the JSONL file) is the primary source for the
 * heuristic working_context fallback; session events from the DB are the
 * primary source for files_modified, decisions, and errors.
 *
 * @param sessionId   - Session UUID.
 * @param projectDir  - Absolute path to the project directory.
 * @param events      - Stored session events from SessionDB.
 * @param workingMem  - Current working memory (for user_preferences, conventions).
 * @param transcript  - Parsed transcript context (may be null).
 * @param compressor  - Optional local SLM compressor for synthesis. When absent
 *                      both headline and working_context are derived heuristically.
 * @param resumeChain - Compaction history chain from getResumeChain(). When present,
 *                      SLM briefs from prior cycles are prepended to the synthesis
 *                      input so the handoff covers the full session arc, not just
 *                      the tail. Pass undefined or empty array for short sessions.
 * @returns HandoffData ready to be written to YAML.
 */
export async function buildHandoffFromEvents(
  sessionId: string,
  projectDir: string,
  events: StoredEvent[],
  workingMem: WorkingMemory | null,
  transcript: TranscriptContext | null,
  compressor?: import("../compression/types.js").Compressor,
  resumeChain?: ResumeHistoryRow[],
): Promise<HandoffData> {
  // Group events by category
  const byCategory: Record<string, StoredEvent[]> = {};
  for (const ev of events) {
    (byCategory[ev.category] ??= []).push(ev);
  }

  const fileEvents     = byCategory["file"]     ?? [];
  const taskEvents     = byCategory["task"]     ?? [];
  const decisionEvents = byCategory["decision"] ?? [];
  const errorEvents    = byCategory["error"]    ?? [];
  const promptEvents   = byCategory["prompt"]   ?? [];

  // files_modified: unique file paths from write/edit events
  const filesModified = [
    ...new Set(
      fileEvents
        .filter(e => e.type === "file_write" || e.type === "file_edit")
        .map(e => e.data)
    ),
  ];

  // decisions: unique decision event data, truncated
  let decisions = [
    ...new Set(decisionEvents.map(e => truncateString(e.data, 200))),
  ].slice(-15);

  // Errors: raw error data
  const allErrors = errorEvents.map(e => truncateString(e.data, 200));
  // Heuristic: last error in the session was likely resolved if no further errors follow.
  // We can't know for sure, so we report all errors and let the user update.
  const errorsEncountered = allErrors.slice(-10);
  const errorsResolved: string[] = [];

  // next_steps: pending tasks from task events
  const creates: string[] = [];
  const updates: Record<string, string> = {};
  for (const ev of taskEvents) {
    try {
      const p = JSON.parse(ev.data) as Record<string, unknown>;
      if (typeof p.subject === "string") creates.push(p.subject);
      else if (typeof p.taskId === "string" && typeof p.status === "string")
        updates[p.taskId] = p.status;
    } catch { /* not JSON */ }
  }
  const DONE = new Set(["completed", "deleted", "failed"]);
  const sortedIds = Object.keys(updates).sort((a, b) => Number(a) - Number(b));
  const nextSteps = creates.filter((_, i) => !DONE.has(updates[sortedIds[i]] ?? "pending")).slice(-10);

  // current_task: last user prompt or transcript's last user message
  const lastPromptEvent = promptEvents.at(-1);
  let currentTask = lastPromptEvent
    ? truncateString(lastPromptEvent.data, 300)
    : (transcript?.user_messages.at(-1) ? truncateString(transcript.user_messages.at(-1)!, 300) : "");

  // last_action: last file write/edit event
  const lastFile = fileEvents.filter(e => e.type === "file_write" || e.type === "file_edit").at(-1);
  const lastAction = lastFile ? `${lastFile.type === "file_write" ? "Wrote" : "Edited"} ${lastFile.data}` : "";

  // open_questions: question events that have no follow-up decision
  const questionEvents = byCategory["decision"]?.filter(e => e.type === "decision_question") ?? [];
  const openQuestions = questionEvents.map(e => truncateString(e.data, 200)).slice(-5);

  // blockers: unresolved errors
  let blockers = allErrors.length > 0 ? allErrors.slice(-3) : [];

  // confidence: high if we have events + transcript, medium if only one, low if neither
  const hasEvents = events.length > 0;
  const hasTranscript = transcript !== null && transcript.user_messages.length > 0;
  const confidence: "high" | "medium" | "low" =
    hasEvents && hasTranscript ? "high" :
    hasEvents || hasTranscript ? "medium" : "low";

  // ── working_context and headline ─────────────────────────────────────────────

  // Heuristic fallback values — used when the SLM is absent or produces nothing.
  const recentMessages = transcript?.user_messages.slice(-3) ?? [];
  const defaultWorkingContext = recentMessages.length > 0
    ? recentMessages.map(m => truncateString(m, 150)).join(" | ")
    : currentTask;
  const defaultHeadline = truncateString(currentTask, 150);

  let workingContext = defaultWorkingContext;
  let headline = defaultHeadline;

  // Use local SLM to synthesize working_context and headline if available.
  // Zero external API calls — only the locally-hosted GGUF model is used.
  // When the SLM supports diff-mode (grammar-constrained JSON), the structured
  // output also enriches decisions, errors, and blockers with SLM analysis.
  if (compressor) {
    // Extract SLM briefs from the compaction chain, oldest first.
    // These cover everything that happened before the final compaction cycle.
    // Prefer slm_brief (semantic synthesis). Fall back to snapshot (structural XML)
    // so even old sessions without SLM briefs benefit from the chain.
    const priorCompactionBriefs = (resumeChain ?? [])
      .map(row => row.slm_brief ?? row.snapshot)
      .filter(Boolean) as string[];

    const synthesisInput = buildSynthesisInput(
      promptEvents, decisionEvents, filesModified, allErrors,
      errorsResolved, currentTask, lastAction,
      priorCompactionBriefs,
    );
    if (synthesisInput.trim()) {
      try {
        const result = await compressor.compress(synthesisInput, 3.0);

        if (result.format === "json" && result.structured) {
          // ── Diff-mode: structured JSON from grammar-constrained SLM ──────
          const s = result.structured;

          // SLM-identified current task overrides heuristic (it resolves conflicts)
          if (s.current_task) currentTask = s.current_task;

          // Synthesis becomes the working context
          if (s.synthesis) workingContext = s.synthesis;

          // Headline from synthesis first sentence
          if (s.synthesis) {
            const firstSentence = s.synthesis.split(/(?<=[.!?])\s/)[0] ?? s.synthesis;
            headline = truncateString(firstSentence.trim(), 150);
          }

          // Enrich decisions with SLM analysis (prepend status for clarity)
          if (s.decisions?.length) {
            const slmDecisions = s.decisions.map(d =>
              `[${d.status}] ${d.topic}: ${d.decision}`
            );
            // Merge: SLM decisions first (they resolved conflicts), then rule-based
            decisions = [...slmDecisions, ...decisions.filter(d =>
              !slmDecisions.some(sd => sd.toLowerCase().includes(d.slice(0, 40).toLowerCase()))
            )].slice(0, 15);
          }

          // Enrich blockers with SLM error analysis
          if (s.errors?.length) {
            const unresolvedFromSLM = s.errors
              .filter(e => e.status !== "RESOLVED")
              .map(e => `[${e.status}] ${e.description}`);
            if (unresolvedFromSLM.length > 0) {
              blockers = unresolvedFromSLM;
            }
          }

          // Next session becomes the next_steps if empty
          if (s.next_session && nextSteps.length === 0) {
            nextSteps.push(s.next_session);
          }

        } else if (result.compressed.trim()) {
          // ── Prose fallback ───────────────────────────────────────────────
          workingContext = result.compressed.trim();
          const firstSentence = result.compressed.split(/(?<=[.!?])\s/)[0] ?? result.compressed;
          headline = truncateString(firstSentence.trim(), 150);
        }
      } catch {
        // SLM unavailable or failed — silently keep heuristic values
      }
    }
  }

  return {
    session_id: sessionId,
    timestamp: new Date().toISOString(),
    project_dir: projectDir,
    current_task: currentTask,
    last_action: lastAction,
    next_steps: nextSteps,
    decisions,
    files_modified: filesModified.slice(-20),
    errors_encountered: errorsEncountered,
    errors_resolved: errorsResolved,
    working_context: workingContext,
    headline,
    user_preferences: workingMem?.user_preferences ?? "",
    codebase_conventions: workingMem?.codebase_conventions ?? "",
    open_questions: openQuestions,
    blockers,
    confidence,
  };
}

// ── Write ─────────────────────────────────────────────────────────────────────

/**
 * Write a HandoffData object to the project's YAML handoff file.
 * Creates the directory if it doesn't exist.
 *
 * @param data       - HandoffData to write.
 * @param projectDir - Absolute path to the project directory.
 * @returns Absolute path to the written handoff file.
 */
export function writeHandoff(data: HandoffData, projectDir: string): string {
  const handoffPath = getHandoffPath(projectDir);
  mkdirSync(dirname(handoffPath), { recursive: true });
  writeFileSync(handoffPath, yaml.dump(data, { lineWidth: 120 }), "utf-8");
  return handoffPath;
}
